baseURL = 'https://clade.post-self.ink/'
languageCode = 'en-us'
title = 'Clade'
theme = 'maddybook'
paginatePath = ''
disablePathToLower = true

[permalinks]
    post = '/:filename/'

[params]
    author = 'The Clade authors'
    home = 'https://post-self.ink'
    copyright = 2023
    customCSS = ['/css/clade.css']
    subtitle = 'A Post-Self Anthology'
    subtitleLink = 'https://post-self.ink'

[markup.goldmark.renderer]
    unsafe = true
